config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", :passwords => "passwords" }

  resources :projects
  resources :catalysts, controller: "campaigns"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "alyst#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :logo
  has_one_attached :background_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/alyst_controller.rb
class AlystController < ApplicationController
  include ActiveStorage::SetCurrent

  def index
    @projects = Project.where(active: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[ show edit update destroy ]

  # GET /campaigns or /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns or /campaigns.json
  def create
    @campaign = Campaign.new(name: params[:name], target_amount: params[:target_amount], period_of_time: params[:period_of_time], contract_address: params[:contract_address])

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to catalyst_url(@campaign), notice: "Campaign was successfully created." }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1 or /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to catalyst_url(@campaign), notice: "Campaign was successfully updated." }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1 or /campaigns/1.json
  def destroy
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to catalysts_url, notice: "Campaign was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def campaign_params
      params.require(:campaign).permit(:name, :target_amount, :period_of_time)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  def new
    flash[:info] = 'Passwords are not open.'
    redirect_to root_path
  end

  def create
    flash[:info] = 'Passwords are not open.'
    redirect_to root_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :is_admin?, only: %i[ edit show index update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.where(active: true)
    @pending_projects = Project.where(active: false)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    
    # Only allow a list of trusted parameters through.
    def project_params
      if current_user&.admin?
        params.require(:project).permit(:name, :category, :website, :discord, :twitter, :github, :logo, :background_image, :active)
      else
        params.require(:project).permit(:name, :category, :website, :discord, :twitter, :github, :logo, :background_image)
      end
    end

    def is_admin?
      redirect_to root_path unless current_user && current_user.admin? 
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    flash[:info] = 'Registrations are not open.'
    redirect_to root_path
  end

  def create
    flash[:info] = 'Registrations are not open.'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/alyst/_project_card.html.erb
<div class="max-w-xs flex flex-col mx-4 w-auto h-96 min-h-300 mb-10 rounded-lg border-solid border-4 overflow-hidden shadow-lg divide-y <%= project.category.gsub(" ", "").downcase %>" data-filter-target="projectCard">  
  <div 
    class="px-6 py-4 min-h-[40%] bg-cover"
    style="background-image: url(<%=  url_for(Rails.application.routes.url_helpers.polymorphic_url(project&.background_image)) %>); background-position: center">
    <span>
      <%= image_tag 'live1.svg', class: "rounded-full shadow-lg h-auto align-left" %>
    </span>
  </div>
  <div class="min-h-max flex-auto bg-white">
    <div>
      <%= image_tag project&.logo, alt: "logo", class: "max-w-[50%] mx-auto -mt-12 rounded-full shadow-lg h-auto align-middle" %>
      <div class="text-center relative -mt-4">
        <a href="<%= project&.website %>" target="_blank">
          <%= image_tag "client_pic_icon_hover.svg", class: "mx-auto" %>
        </a>
      </div>
    </div>
    <div class="px-6 pt-4 pb-2 lg:pb-0 sm:pb-0 text-center">
      <p><%= project&.name %></p>
    </div>
    <div class="px-6 pt-4 pb-2 lg:pb-0 sm:pb-0 text-center">
      <p><%= project&.category %></p>
    </div>
    <div class="pt-4 pb-2 lg:pb-0 sm:pb-0 text-center">
      <% if project&.discord != "" %>
          <a href="<%= project&.discord %>" class="mx-4" target="_blank">
          <i class="fa-brands fa-discord text-2xl"></i>
        </a>
      <% end %>

      <% if project&.twitter != "" %>
        <a href="<%= project&.twitter %>" class="mx-4 inline-block" target="_blank">
          <i class="fa-brands fa-twitter text-2xl"></i>
        </a>
      <% end %>

      <% if project&.github != "" %>
        <a href="<%= project&.github %>" class="inline-block mx-4" target="_blank">
          <i class="fa-brands fa-github text-2xl"></i>
        </a>
      <% end %>
    </div>
  </div>
</div>

app/views/alyst/index.html.erb
<div class="h-96" style="background: linear-gradient(90deg, #4ba260 0%, #1A4525 100%)">
  <div class="items-center flex">
    <div class="text-white mx-auto hidden md:flex" style="font-family: 'Perpetua Titling MT', sans-serif;">
      <p>Beta</p>
      <h1 class="text-7xl" style="font-family: 'Perpetua Titling MT', sans-serif;">Canto Portal</h1>
    </div>
  </div>
  <div class="items-center flex hidden md:flex">
    <h3 class="text-white text-xl mx-auto" style="font-family: 'Perpetua Titling MT', sans-serif;">Your gateway into the Canto ecosystem</h3>
  </div>
  <div class="items-center flex md:hidden">
    <h3 class="text-white text-xl mx-auto" style="font-family: 'Perpetua Titling MT', sans-serif;">Your gateway into</h3>
  </div>
  <div class="items-center flex md:hidden">
    <h3 class="text-white text-xl mx-auto" style="font-family: 'Perpetua Titling MT', sans-serif;">the Canto ecosystem</h3>
  </div>
  <div class="flex justify-center mt-12">
    <button data-action="click->filter#filterCard" data-value="defi" class="bg-transparent border hover:bg-green-200 text-white font-bold py-2 px-4 rounded-full mx-1" style="font-family: 'Perpetua Titling MT', sans-serif;">Defi</button>
    <button data-action="click->filter#filterCard" data-value="ecosystem" class="bg-transparent border hover:bg-green-200 text-white font-bold py-2 px-4 rounded-full mx-1" style="font-family: 'Perpetua Titling MT', sans-serif;">Ecosystem</button>
    <button data-action="click->filter#filterCard" data-value="nft" class="bg-transparent border hover:bg-green-200 text-white font-bold py-2 px-4 rounded-full mx-1" style="font-family: 'Perpetua Titling MT', sans-serif;">NFT</button>
    <button data-action="click->filter#filterCard" data-value="newthings" class="bg-transparent border hover:bg-green-200 text-white font-bold py-2 px-4 rounded-full mx-1" style="font-family: 'Perpetua Titling MT', sans-serif;">New Things</button>
  </div>
</div>

<div class="container mx-auto">
  <div class="grid lg:grid-cols-4 md:grid-cols-2 place-items-center md:-mt-40 -mt-56">
    <% @projects.each do |project| %>
      <%= render "project_card", project: project %>
    <% end %>
  </div>
</div>

app/views/alyst/panalyst.html.erb
<div class="h-96" style="background: linear-gradient(90deg, #4ba260 0%, #1A4525 100%)">
  <div class="items-center flex">
    <h1 class="text-white text-7xl mx-auto" style="font-family: 'Perpetua Titling MT', sans-serif;">Canto Portal</h1>
    <%# <h3 class="text-white text-xl ">Your gateway into the Canto ecosystem</h3> %>
  </div>
  <div class="items-center flex">
    <%# <h1 class="text-white text-7xl mx-auto">Canto Portal</h1> %>
    <h3 class="text-white text-xl mx-auto" style="font-family: 'Perpetua Titling MT', sans-serif;">Your gateway into the Canto ecosystem</h3>
  </div>
  <div class="flex justify-center mt-12">
    <button data-action="click->filter#filterCard" data-value="defi" class="bg-transparent border hover:bg-green-200 text-white font-bold py-2 px-4 rounded-full mx-1" style="font-family: 'Perpetua Titling MT', sans-serif;">Defi</button>
    <button data-action="click->filter#filterCard" data-value="ecosystem" class="bg-transparent border hover:bg-green-200 text-white font-bold py-2 px-4 rounded-full mx-1" style="font-family: 'Perpetua Titling MT', sans-serif;">Ecosystem</button>
    <button data-action="click->filter#filterCard" data-value="nft" class="bg-transparent border hover:bg-green-200 text-white font-bold py-2 px-4 rounded-full mx-1" style="font-family: 'Perpetua Titling MT', sans-serif;">NFT</button>
    <button data-action="click->filter#filterCard" data-value="newthings" class="bg-transparent border hover:bg-green-200 text-white font-bold py-2 px-4 rounded-full mx-1" style="font-family: 'Perpetua Titling MT', sans-serif;">New Things</button>
  </div>
</div>

<div class="container mx-auto">
  <div class="grid lg:grid-cols-4 md:grid-cols-2 place-items-center -mt-40">
    <% @projects.each do |project| %>
      <%= render "project_card", project: project %>
    <% end %>
  </div>
</div>

<%# style="background: linear-gradient(90deg, #4ba260 0%, #1A4525 100%)" %>

app/views/campaigns/_campaign.html.erb
<%= link_to catalyst_path(campaign) do %>
  <div id="<%= dom_id campaign %>" class="border border-solid w-1/2 py-6 px-5 flex flex-row">
    <div class="h-28 w-28 flex items-center justify-center">
      <%= image_tag 'cantocrabs-logo.jpeg', class: "shadow-lg h-auto align-left max-h-full max-w-full object-cover object-center" %>
    </div>
    <div class="flex flex-col max-w-[50%]">
      <div class="ml-5">
        <h2 class="m-0 overflow-hidden overflow-ellipsis text-xl leading-8 text-black dark:text-slate-100">Crypto Underworld Podcast Bootstrap<%#= campaign.name %></h2>
      </div>

      <div class="ml-5">
        <span>$<%= campaign.target_amount %></span>
        <span class="text-gray-500 dark:text-gray-300"> since <%= campaign.period_of_time.strftime('%Y-%m-%d')  %></span>
      </div>

      <div class="ml-5 max-h-5 overflow-hidden overflow-ellipsis text-grey-400 dark:text-slate-200">
        <%#= campaign.description %>
        Crypto Underworld Podcast comes from the AFA/LCD discussions breaking down the scams we find and investigating how they work and who are behind them.
        We think there is a massive disservice to the crypto community and new users to not have an easy place to listen in for "buyer beware" verbose as well as coverage on crypto fundamentals, self-regulation, and everything in-between.
        No shilling projects, no covering the price of BTC day to day, just pure talk and a few guests here and
      </div>
    </div>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing campaign</h1>

  <%= render "form", campaign: @campaign %>

  <%= link_to "Show this campaign", @campaign, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to campaigns", catalysts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/campaigns/index.html.erb
<div class="h-96 container mx-auto p-5">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex items-center">
    <h1 class="font-bold text-4xl mx-auto">Catalysts on Alyst</h1>
    <%= link_to 'New campaign', new_catalyst_path, class: "rounded-lg py-3 px-5 bg-blue-600 mx-auto text-white block font-medium" %>
  </div>

  <div class="flex items-center">
    <p>
      The Juicebox protocol is open to anyone, and project configurations can vary widely.
      There are risks associated with interacting with all projects on the protocol. 
      Projects built on the protocol are not endorsed or vetted by JuiceboxDAO or Peel.
      Do your own research and understand the risks before committing your funds.
    </p>
  </div>

  <div id="campaigns" class="min-w-full flex">
    <%= render @campaigns %>
  </div>
</div>

app/views/campaigns/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div>
    <h1 class="text-black text-7xl">Projects on Catalyst</h1>
    <p class="text-black text-xl">The Catalyst protocol is open to anyone, and project configurations can vary widely. There are risks associated with interacting with all projects on the protocol. 
    Projects built on the protocol are not endorsed or vetted by Alyst.
    Do your own research and understand the risks before committing your funds.</p>
  </div>

  <%= render "form", campaign: @campaign %>

  <%= link_to 'Back to campaigns', catalysts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/campaigns/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @campaign %>

    <%#= link_to 'Edit this campaign', edit_catalyst_path(@campaign), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <p class="hidden" data-ethers-target="contractAddress"><%= @campaign.contract_address %></p>
      <button data-action="click->ethers#pledgeToCampaign" class="mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium">Contribute to campagin</button>
      <%#= button_to 'Destroy this campaign', catalyst_path(@campaign), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <div class="inline-block ml-2">
      <p class="hidden" data-ethers-target="contractAddress"><%= @campaign.contract_address %></p>
      <button data-action="click->ethers#withdrawFunds" class="mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium">Withdraw from campagin</button>
      <%#= button_to 'Destroy this campaign', catalyst_path(@campaign), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to campaigns', catalysts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alyst</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="ethers" class="min-h-screen">
    <nav style="background: linear-gradient(90deg, #4ba260 0%, #1A4525 100%)">
      <div class="container mx-auto px-6 py-2 flex justify-between items-center">
        <a class="w-48" href="https://alyst.xyz">
          <%= image_tag("AlystSVG2.svg", :alt => "Alyst") %>
        </a>
        <div class="block md:hidden">
          <ul class="inline-flex">
            <li class="text-white text-right"  style="font-family: 'Perpetua Titling MT', sans-serif;"><%= link_to "Add Project", new_project_path, class: "px-4" %></li>
          </ul>
          <%# <button class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-800 hover:border-teal-500 appearance-none focus:outline-none">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <title>Canto</title>
              <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
            </svg>
          </button> %>
        </div>

        <div class="hidden md:block">
          <ul class="inline-flex">
            <% if user_signed_in? %>
              <li class="text-white"  style="font-family: 'Perpetua Titling MT', sans-serif;"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% end %>

            <li class="text-white"  style="font-family: 'Perpetua Titling MT', sans-serif;"><a class="px-4" href="https://evm.explorer.canto.io/" target="_blank">Canto Explorer</a></li>
            <li class="text-white"  style="font-family: 'Perpetua Titling MT', sans-serif;"><%= link_to "Apply To Join PanAlyst", new_project_path, class: "px-4" %></li>
            <li class="text-white"  style="font-family: 'Perpetua Titling MT', sans-serif;"><a class="px-4" href="https://canto.io/bridge" target="_blank">Canto Bridge</a></li>
            <%# <li class="text-white"  style="font-family: 'Perpetua Titling MT', sans-serif;"><a data-action="click->ethers#connectWallet" data-ethers-target="etherState" class="px-4 hover:text-gray-800" href="#">Connect</a></li>
            <li class="text-white"  style="font-family: 'Perpetua Titling MT', sans-serif;"><p class="showAccount hidden" data-ethers-target="etherState"></p></li> %>
          </ul>
        </div>
      </div>
    </nav>
    <main data-controller="filter">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <footer class="bg-gray-100 sticky top-[100vh]" style="background: linear-gradient(90deg, #4ba260 0%, #1A4525 100%)">
      <div class="container mx-auto px-6 pt-10 pb-6">
        <div class="flex justify-center">
          <div >
            <div>
              <div>
                <%= image_tag("AlystSVG2.svg", :alt => "Alyst") %>
              </div>
            </div>
            <div class="mt-6 text-center">
              <%# <li class="mx-4 inline-block"><a href="https://discord.gg/arbitrum" target="_blank"><i class="fab fa-discord" aria-hidden="true"></i></a></li> %>
              <li class="mx-4 inline-block text-white"><a href="https://twitter.com/alyst_xyz" target="_blank"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
              <li class="mx-4 inline-block text-white"><a href="https://github.com/alystxyz/alyst" target="_blank"><i class="fab fa-github" aria-hidden="true"></i></a></li>
            </div>

            <div class="mt-4 text-center">
              <div>
                <div>
                  <p class="text-white">© AlystXYZ, Inc. 2022. All Rights Reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= project.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= project.category %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Website:</strong>
    <%= project.website != "" ? project.website : "NA" %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Discord:</strong>
    <%= project.discord != "" ? project.discord : "NA" %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Twitter:</strong>
    <%= project.twitter != "" ? project.twitter : "NA" %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Github:</strong>
    <%= project.github || "NA" %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Logo:</strong>
    <%= link_to project.logo.filename, project.logo if project.logo.attached? %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Background image:</strong>
    <%= link_to project.background_image.filename, project.background_image if project.background_image.attached? %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <% if user_signed_in? %> 
    <h1 class="font-bold text-4xl">Editing project</h1>

    <%= render "form", project: @project %>

    <%= link_to "Show this project", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <% else %>
    <%= button_to "Sign in", new_user_session_path %> 
  <% end %>
</div>

app/views/projects/index.html.erb
<div class="w-full">
  <% if user_signed_in? %> 
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

  <% if @pending_projects.count > 0 %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Pending Projects</h1>
      <%#= link_to 'New project', new_project_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>

    <div id="projects" class="grid grid-cols-3 gap-3">
      <%= render @pending_projects %>
    </div>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <%#= link_to 'New project', new_project_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="projects" class="grid grid-cols-3 gap-3">
    <%= render @projects %>
  </div>
  <% else %>
    <%= button_to "Sign in", new_user_session_path %> 
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if user_signed_in? %> 
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>

      <%= render @project %>

      <%= link_to 'Edit this project', edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this project', project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
      <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% else %>
      <%= button_to "Sign in", new_user_session_path %> 
    <% end %>
  </div>
</div>